#!/bin/sh

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap


# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi


# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


# disable dpms and screen blanking
xset -dpms
xset s off


# set keymap
setxkbmap -layout gb


# enable numlock
numlockx &


# load user xresources

if [ -f ~/.config/xorg/xresources ]; then
    xrdb ~/.config/xorg/xresources
fi


# launch herbstluftwm

exec herbstluftwm
